### ISSUE TITLE
bomb error 

### ISSUE THREAD

**Issue by john-whick-13** [Nico-Curti/pyhide#2] opened 2023-10-02 06:37 UTC
thanks for the tool but i got this error 

(myenv) D:\PythonRAT-final\client>pyhide --input customer.py --output encCustomer.py
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Mobco-2031\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\Scripts\pyhide.exe\__main__.py", line 7, in <module>
  File "C:\Users\Mobco-2031\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pyhide\__main__.py", line 200, in main
    obf_code = set_time_bomb(code=obf_code, bomb=bomb, position=0)
                                                 ^^^^
UnboundLocalError: cannot access local variable 'bomb' where it is not associated with a value

**Comment by Nico-Curti** [comment] 2023-10-02 08:28
Hi @john-whick-13 
There was a mistake in my latest commit since I'm still working on the encoded timer.
With the latest commit everything should work well... as described in the tests of the code

**Comment by john-whick-13** [comment] 2023-10-02 09:49
ModuleNotFoundError: No module named 'pytest'

**Comment by Nico-Curti** [comment] 2023-10-02 09:56
I use `pytest` to perform the testing of the package so it must be installed if you want to run the tests...
However, for sake of completeness I added the minimum required packages also for the testing in the corresponding [requirements.txt](https://github.com/Nico-Curti/pyhide/blob/main/test/requirements.txt) file.
If you want to see a complete installation behavior from scratch you can take a look at the [action file](https://github.com/Nico-Curti/pyhide/blob/main/.github/workflows/python.yml) 😉

**Comment by Nico-Curti** [comment] 2023-10-02 10:06
The test folder provides test of the entire package to monitor the behavior of the code in different situations and check the correctness of the functions... it is only for dev purposes.
If you want to use the code you can simply install the package and run the command line interface as described in the [README](https://github.com/Nico-Curti/pyhide/blob/main/README.md#usage) documentation.

**Comment by john-whick-13** [comment] 2023-10-02 10:12
i got this error 

AttributeError: 'Attribute' object has no attribute 'id'
PS D:\PythonRAT-final\client> pyhide --help
usage: pyhide [-h] [--version] --input INPTFILE [--output OUTFILE] [--variable] [--function] [--class] [--pkg] [--num]
              [--str] [--bomb TIME_BOMB]

**Comment by Nico-Curti** [comment] 2023-10-02 10:16
First of all, according to the output of the help, you are not using the latest version of the code.
Please **pull** the repository before.

If you have an error related to the `ast` package, it means that you are working with an incorrect version of Python.
As described in the documentation, a `Python >= 3.8` version is [required](https://github.com/Nico-Curti/pyhide/#installation) for the correct usage of the package.

**Comment by john-whick-13** [comment] 2023-10-02 10:32
is this the last version ...

Requirement already satisfied: pyhide in c:\users\mobco-2031\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (0.0.1)

**Comment by Nico-Curti** [comment] 2023-10-02 10:33
Yes but you are not working with the latest commit, otherwise the --bomb argument should not appear in the command line

**Comment by john-whick-13** [comment] 2023-10-02 10:47
So how can i use latest commit

**Comment by Nico-Curti** [comment] 2023-10-02 10:52
git pull

**Comment by Nico-Curti** [comment] 2023-10-02 11:06
I close this issue since the code has been changed removing the bomb variable in the latest commit (ref [here](https://github.com/Nico-Curti/pyhide/commit/92b4af7bf8fe8da5caf4d7e1f1f51067541a9853))

**Closed by Nico-Curti** 2023-10-02 11:06 UTC

**Comment by john-whick-13** [comment] 2023-10-02 11:11
i already did this but got this error 

pyhide : The term 'pyhide' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a
path was included, verify that the path is correct and try again.
At line:1 char:1
+ pyhide
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (pyhide:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by Nico-Curti** [comment] 2023-10-02 11:17
If you followed all the installation instruction correctly (aka git pull + run the setup succesfully), this error may be due to an incorrect environment path setting.
You probably haven't set all the Python path variables, but I can't help you further since the problem is not related to the pyhide package itself but to your machine's configuration.
